[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# Production-Kontext (wird f端r die Haupt-URL family-toolbox.netlify.app als STAGE verwendet)
[context.production]
  command = "npm run build"
  
  [context.production.environment]
    NEXTAUTH_URL = "https://family-toolbox.netlify.app"

# Platzhalter f端r den zuk端nftigen Live-Kontext (family-toolbox.de)
[context.future-production]
  # command = "npm run build"
  # [context.future-production.environment]
  #   NEXTAUTH_URL = "https://family-toolbox.de"

# Netlify Functions Konfiguration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects f端r SPA-Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# API-Proxying
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 