[build]
  command = "npm run build || echo 'Build had errors but continuing deployment'"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Production-Kontext (wird für die Haupt-URL family-toolbox.netlify.app als STAGE verwendet)
[context.production]
  command = "npm run build || echo 'Build had errors but continuing deployment'"
  
  [context.production.environment]
    NEXTAUTH_URL = "https://family-toolbox.netlify.app"

# Platzhalter für den zukünftigen Live-Kontext (family-toolbox.de)
[context.future-production]
  # command = "npm run build"
  # [context.future-production.environment]
  #   NEXTAUTH_URL = "https://family-toolbox.de" 